services:

  grafana-otel-collector:
    image: grafana/otel-lgtm:0.7.3
    container_name: otel-lgtm
    env_file:
      - .env
    volumes:
      - ./otel-collector-config.yaml:/otel-lgtm/otelcol-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "3000:3000"   # Grafana UI
      - "3200:3200"   # Tempo
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
