receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

processors:
  batch:
  attributes/user: # This processor will redact the "user" field any spans with the name "known-span-with-sensitive-attributes"
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor
    include:
      match_type: strict
      span_names:
        - "known-span-with-sensitive-attributes"
    actions:
      - key: user
        action: upsert
        value: "{redacted}"
      - key: redacted_span
        value: true
        action: upsert
  filter/pii: # This processor will filter out any spans and events with the attribute "has_pii" set to "true"
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
    error_mode: ignore
    traces:
      span:
        - 'attributes["has_pii"] == "true"'
      spanevent:
        - 'attributes["has_pii"] == "true"'

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/pii, attributes/user, batch]
      exporters: [zipkin]
    traces/2:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]